CREATE TABLE PROFESOR 
(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(10),
	APELLIDO1 VARCHAR2(10),
	APELLIDO2 VARCHAR2(10),
	DIRECCION VARCHAR2(40),
	TITULACION VARCHAR2(50),
	CUOTA DECIMAL(15,2),
	CONSTRAINT PK_PROFESOR PRIMARY KEY (DNI)
);

CREATE TABLE CURSO
(
	CODIGO NUMBER(4),
	NOMBRE VARCHAR2(10),
	NUM_MAX_ALUMN NUMBER(5),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	NUM_HORAS NUMBER(3),
	DNI_PROFESOR VARCHAR2(9),
	CONSTRAINT PK_CURSO PRIMARY KEY (CODIGO),
	CONSTRAINT FK1_CURSO FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESOR(DNI)
);

CREATE TABLE ALUMNOS
(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(10),
	APELLIDO1 VARCHAR2(20),
	APELLIDO2 VARCHAR2(20),
	DIRECCION VARCHAR2(40),
	FECHANAC DATE,
	SEXO VARCHAR2(1),
	CURSO NUMBER(4),
	CONSTRAINT PK_ALUMNOS PRIMARY KEY (CODIGO),
	CONSTRAINT FK1_ALUMNOS FOREIGN KEY (CURSO) REFERENCES CURSO(CODIGO),
	CONSTRAINT CHK1_ALUMNOS CHECK (SEXO IN ('V','M'))
);

INSERT INTO PROFESOR(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,TITULACION,CUOTA)
VALUES ('Juan','Arch','López','32432455','Puerta Negra, 4','Ing. Informática',7500);

INSERT INTO PROFESOR(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,TITULACION,CUOTA)
VALUES ('María','Oliva','Rubio','43215643','Juan Alfonso 32','Lda. Fil. Inglesa',5400);

INSERT INTO CURSO(NOMBRE,CADIGO,DNI_PROFESOR,NUM_MAX_ALUMN,FECHA_INICIO,FECHA_FIN,NUM_HORAS)
VALUES ('Inglés Básico', 1, '43215643', 15, TO DATE('01/11/00', 'DD/MM/YY') TO DATE('22-DIC-00', 'DD-MON-YY'), 120);

INSERT INTO CURSO(NOMBRE,CADIGO,DNI_PROFESOR,NUM_MAX_ALUMN,FECHA_INICIO,FECHA_FIN,NUM_HORAS)
VALUES ('Administración Linux', 2, '32432455',NULL, TO DATE('01-SEPT-00', 'DD-MONT-YY'),NULL, 80);

INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,FECHANAC,CURSO)
VALUES ('Lucas', 'Manilva', 'López', '123523', 'Alhamar, 3', 'V', TO DATE('01/11/79', 'DD/MM/YY'), 1);

INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,FECHANAC,CURSO)
VALUES ('Antonia', 'López', 'Alcantara', '2567567', 'Maniquí, 21', 'M',NULL, 2);

INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,FECHANAC,CURSO)
VALUES ('Manuel', 'Alcantara', 'Pedrós', '3123689', 'Julian, 2', '2',NULL, 1);/*AQUÍ DARÍA UN ERROR, YA QUE NO PUEDO INSERTAR '2' EN LA COLUMNA SEXO*/

INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,FECHANAC,CURSO)
VALUES ('José', 'Pérez', 'Caballar', '4896765', 'Jarcha,5', 'V', TO DATE('03/02/77','DD/MM/YY'), 3);

INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,FECHANAC,CURSO)
VALUES ('Sergio', 'Navas', 'Retal', '123523',NULL, 'P',NULL, 1);/*AQUÍ TAMBIÉN DARÍA ERROR POR LA MISMA RAZÓN*/

INSERT INTO PROFESOR(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,TITULACION,CUOTA)
VALUES ('Juan', 'Arch', 'López', '32432455', 'Puerta Negra, 4', 'Ing. Informática', NULL);

INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,FECHANAC)
VALUES ('María', 'Jaén', 'Sevilla', '789678', 'Martos, 5', 'M',NULL);

UPDATE ALUMNOS
SET FECHANAC LIKE TO DATE('23/12/76','DD/MM/YY')
WHERE NOMBRE='Antonia' AND APELLIDO1='López';

UPDATE ALUMNOS
SET CURSO=5
WHERE NOMBRE='Antonia' AND APELLIDO1='López';

DELETE FROM PROFESOR
WHERE NOMBRE='Laura' AND APELLIDO1='Jiménez';

DELETE FROM CURSO
WHERE CODIGO=1;

ALTER TABLE ALUMNOS
ADD COLUMN NUMERO_ALUMNOS NUMBER(4);

ALTER TABLE ALUMNOS
MODIFY COLUMN FECHANAC DATE DEFAULT TO DATE('01/01/2012','DD/MM/YYYY');

ALTER TABLE ALUMNOS
DROP COLUMN SEXO;

ALTER TABLE PROFESOR
MODIFY COLUMN CUOTA=CUOTA*1.2
WHERE TITULACION LIKE '%Informática';

UPDATE PROFESOR
SET DNI='1234567'
WHERE NOMBRE='Juan' AND APELLIDO1='Arch';

UPDATE PROFESOR
SET DNI='7654321'
WHERE TITULACION LIKE '%Informática';/*ESTE UPDATE DARÍA UN ERROR PORQUE LA CLAVE PRIMARIA DNI NO PUEDE ESTAR DUPLICADA*/

UPDATE ALUMNOS
SET SEXO='F'
WHERE NOMBRE='María' AND APELLIDO1='Jaén';




