CREATE TABLE FAMILIA (
    ID_FAMILIA NUMBER(4),
    NOMBRE VARCHAR2(10),
    CONSTRAINT PK_FAMILIA PRIMARY KEY (ID_FAMILIA)
);

CREATE TABLE GENERO (
    ID_GENERO NUMBER(4),
    NOMBRE VARCHAR2(10),
    ID_FAMILIA NUMBER(4),
    CONSTRAINT PK_GENERO PRIMARY KEY (ID_GENERO),
    CONSTRAINT FK1_GENERO FOREIGN KEY (ID_FAMILIA) REFERENCES FAMILIA(ID_FAMILIA)
);

CREATE TABLE ESPECIE (
    ID_ESPECIE NUMBER(4),
    NOMBRE VARCHAR2(10),
    ID_GENERO NUMBER(4),
    CONSTRAINT PK_ESPECIE PRIMARY KEY (ID_ESPECIE),
    CONSTRAINT FK1_ESPECIE FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO)
);

CREATE TABLE ZONA (
    ID_ZONA NUMBER(4),
    PROTEGIDA VARCHAR2(2),
    EXTENSION NUMBER(6),
    LOCALIDAD VARCHAR2(100),
    NOMBRE VARCHAR2(10),
    CONSTRAINT PK_ZONA PRIMARY KEY (ID_ZONA),
    CONSTRAINT CHK1_ZONA CHECK (PROTEGIDA IN ('Si','No'))
);

CREATE TABLE PERSONA (
    ID_PERSONA NUMBER(4),
    NOMBRE VARCHAR2(10) NOT NULL,
    DNI VARCHAR2(20),
    TELEFONO VARCHAR2(15),
    DIRECCION VARCHAR2(200),
    CONSTRAINT PK_PERSONA PRIMARY KEY (ID_PERSONA)
);

CREATE TABLE COLECCION (
    ID_COLECCION NUMBER(4),
    NUM_EJEMPLARES NUMBER(3),
    FECHA_INICIO DATE,
    PRECIO NUMBER(10),
    CONSTRAINT PK_COLECCION PRIMARY KEY (ID_COLECCION),
    CONSTRAINT CHK1_COLECCION CHECK (NUM_EJEMPLARES BETWEEN 1 AND 150)
);

CREATE TABLE EJEMPLAR_MARIPOSA (
    NOMBRE_COMUN VARCHAR2(10),
    PRECIO_EJEMPLAR NUMBER(10),
    FECHA_CAPTURA DATE,
    HORA_CAPTURA VARCHAR2(8),
    FECHA_COLECCION DATE,
    ID_ESPECIE NUMBER(4),
    ID_ZONA NUMBER(4),
    ID_PERSONA NUMBER(4),
    ID_COLECCION NUMBER(4),
    CONSTRAINT PK_EJEMPLAR_MARIPOSA PRIMARY KEY (FECHA_CAPTURA,HORA_CAPTURA,ID_ZONA,ID_ESPECIE,ID_PERSONA),
    CONSTRAINT FK1_EJEMPLAR_MARIPOSA FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE(ID_ESPECIE),
    CONSTRAINT FK2_EJEMPLAR_MARIPOSA FOREIGN KEY (ID_ZONA) REFERENCES ZONA(ID_ZONA),
    CONSTRAINT FK3_EJEMPLAR_MARIPOSA FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA),
    CONSTRAINT FK4_EJEMPLAR_MARIPOSA FOREIGN KEY (ID_COLECCION) REFERENCES COLECCION(ID_COLECCION),
    CONSTRAINT CHK1_EJEMPLAR_MARIPOSA CHECK (PRECIO_EJEMPLAR>0)
);

ALTER TABLE PERSONA
ADD APELLIDOS VARCHAR2(20);

ALTER TABLE ZONA
ADD CONSTRAINT CHK2_ZONA CHECK (EXTENSION BETWEEN 100 AND 1500);

ALTER TABLE EJEMPLAR_MARIPOSA
DROP CONSTRAINT CHK1_EJEMPLAR_MARIPOSA;

ALTER TABLE EJEMPLAR_MARIPOSA
MODIFY FECHA_CAPTURA DATE DEFAULT SYSDATE;
