CREATE TABLE DEPARTAMENTO
(
	CODIGO NUMBER(10),
	NOMBRE VARCHAR2(100),
	PRESUPUESTO DECIMAL,
	GASTOS DECIMAL,
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (CODIGO)
);

CREATE TABLE EMPLEADO
(
	CODIGO NUMBER(10),
	NIF VARCHAR2(9),
	NOMBRE VARCHAR2(100),
	APELLIDO1 VARCHAR2(100),
	APELLIDO2 VARCHAR2(100),
	CODIGO_DEPARTAMENTO NUMBER(10),
	CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGO),
	CONSTRAINT FK1_EMPLEADO FOREIGN KEY (CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO)
);

CREATE SEQUENCE SEQ_DEPARTAMENTO
START WITH 1
INCREMENT BY 1;

INSERT INTO DEPARTAMENTO
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Desarrollo', 120000, 6000);

INSERT INTO DEPARTAMENTO
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Sistemas', 150000, 21000);

INSERT INTO DEPARTAMENTO
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Recursos Humanos', 280000, 25000);

INSERT INTO DEPARTAMENTO
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Contabilidad', 110000, 3000);

INSERT INTO DEPARTAMENTO
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'I+D', 375000, 380000);

INSERT INTO DEPARTAMENTO
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Proyectos', 0, 0);

INSERT INTO DEPARTAMENTO
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Publicidad', 0, 1000);

CREATE SEQUENCE SEQ_EMPLEADO
START WITH 1
INCREMENT BY 1;

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '32481596F', 'Aarón', 'Rivero', 'Gómez', 1);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, 'Y5575632D', 'Adela', 'Salas', 'Díaz', 2);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, 'R6970642B', 'Adolfo', 'Rubio', 'Flores', 3);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '77705545E', 'Adrián', 'Suárez', NULL, 4);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '17087203C', 'Marcos', 'Loyola', 'Méndez', 5);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '38382980M', 'María', 'Santana', 'Moreno', 1);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '80576669X', 'Pilar', 'Ruiz', NULL, 2);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '71651431Z', 'Pepe', 'Ruiz', 'Santana', 3);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '56399183D', 'Juan', 'Gómez', 'López', 2);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '46384486H', 'Diego','Flores', 'Salas', 5);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '67389283A', 'Marta','Herrera', 'Gil', 1);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '41234836R', 'Irene','Salas', 'Flores', NULL);

INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '82635162B', 'Juan Antonio','Sáez', 'Guerrero', NULL);

--1. Inserta un nuevo departamento indicando su código, nombre y presupuesto.
INSERT INTO DEPARTAMENTO(CODIGO,NOMBRE,PRESUPUESTO)
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Atención al cliente', 15000);

--2. Inserta un nuevo departamento indicando su nombre y presupuesto.
INSERT INTO DEPARTAMENTO(NOMBRE,PRESUPUESTO)
VALUES ('Gestión de proveedores', 160000);/*VA A DAR UN ERROR, YA QUE DEBE INTRODUCIRSE TAMBIÉN LA CLAVE PRIMARIA*/

--3. Inserta un nuevo departamento indicando su código, nombre, presupuesto y gastos.
INSERT INTO DEPARTAMENTO
VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Gestión de clientes', 150000, 380000);

--4. Inserta un nuevo empleado asociado a uno de los nuevos departamentos. La sentencia de inserción debe incluir: código, nif, nombre, apellido1, apellido2 y codigo_departamento.
INSERT INTO EMPLEADO
VALUES (SEQ_EMPLEADO.NEXTVAL, '67389283B', 'Jesús', 'Morilla', 'Martínez', 8);

--5. Inserta un nuevo empleado asociado a uno de los nuevos departamentos. La sentencia de inserción debe incluir: nif, nombre, apellido1, apellido2 y codigo_departamento.
INSERT INTO EMPLEADO(NIF,NOMBRE,APELLIDO1,APELLIDO2,CODIGO_DEPARTAMENTO)
VALUES ('Y5575632F', 'Marta', 'López', 'Martos', 8);

--6. Crea una nueva tabla con el nombre departamento_backup que tenga las mismas columnas que la tabla departamento. Una vez creada copia todos las filas de tabla departamento en departamento_backup.
CREATE TABLE DEPARTAMENTO_BACKUP
(
	CODIGO NUMBER(10),
	NOMBRE VARCHAR2(100),
	PRESUPUESTO DECIMAL,
	GASTOS DECIMAL,
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (CODIGO)
	
);

INSERT INTO DEPARTAMENTO_BACKUP
SELECT CODIGO, NOMBRE, PRESUPUESTO, GASTOS
FROM DEPARTAMENTO;

--7. Elimina el departamento Proyectos. ¿Es posible eliminarlo? Si no fuese posible, ¿qué cambios debería realizar para que fuese posible borrarlo?
DELETE FROM DEPARTAMENTO
WHERE NOMBRE LIKE 'Proyectos';/*SI ES POSIBLE ELIMINARLO, YA QUE NO HAY NINGÚN EMPLEADO ENLAZADO A ESE DEPARTAMENTO*/

--8. Elimina el departamento Desarrollo. ¿Es posible eliminarlo? Si no fuese posible, ¿qué cambios debería realizar para que fuese posible borrarlo?
DELETE FROM DEPARTAMENTO
WHERE NOMBRE LIKE 'Desarrollo';/*NO ES POSIBLE BORRARLO, YA QUE EXISTEN EMPLEADOS ENLAZADOS A ESE DEPARTAMENTO. LO QUE SE DEBERÍA HACER ANTES ES ELIMINAR LA COLUMNA DE CODIGO_DEPARTAMENTO EN AQUELLOS EMPLEADOS CON UN 1*/

--9. Actualiza el código del departamento Recursos Humanos y asígnale el valor 30. ¿Es posible actualizarlo? Si no fuese posible, ¿qué cambios deberíarealizar para que fuese actualizarlo?
UPDATE DEPARTAMENTO
SET CODIGO=30
WHERE NOMBRE LIKE 'Recursos Humanos';/*NO SERÍA POSIBLE PORQUE EXISTEN EMPLEADOS ENLAZADOS A ESE DEPARTAMENTO. SE DEBERÍAN ACTUALIZAR ANTES LAS COLUMNAS EN LOS EMPLEADOS CORRESPONDIENTES*/

--10. Actualiza el código del departamento Publicidad y asígnale el valor 40. ¿Es posible actualizarlo? Si no fuese posible, ¿qué cambios debería realizar para que fuese actualizarlo?
UPDATE DEPARTAMENTO
SET CODIGO=40
WHERE NOMBRE LIKE 'Publicidad';/*EN ESTE CASO SI SE PODRÍA ACTUALIZAR DEBIDO A QUE NO EXISTEN EMPLEADOS ENLAZADOS A ESE DEPARTAMENTO*/

--11. Actualiza el presupuesto de los departamentos sumándole 50000 € al valor del presupuesto actual, solamente a aquellos departamentos que tienen un presupuesto menor que 20000 €.
UPDATE DEPARTAMENTO
SET PRESUPUESTO=PRESUPUESTO+50000
WHERE PRESUPUESTO<20000;

--12. Realiza una transacción que elimine todas los empleados que no tienen un departamento asociado.
DELETE FROM EMPLEADO
WHERE CODIGO_DEPARTAMENTO=NULL;

/*OPCIÓN APARTE DE HACER UN BACKUP DE LA TABLA EMPLEADO*/
CREATE TABLE EMPLEADO_BACKUP
(
	CODIGO NUMBER(10),
	NIF VARCHAR2(9),
	NOMBRE VARCHAR2(100),
	APELLIDO1 VARCHAR2(100),
	APELLIDO2 VARCHAR2(100),
	CODIGO_DEPARTAMENTO NUMBER(10),
	CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGO),
	CONSTRAINT FK1_EMPLEADO FOREIGN KEY (CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO)
	
);

INSERT INTO EMPLEADO_BACKUP
SELECT CODIGO, NIF, NOMBRE, APELLIDO1, APELLIDO2, AODIGO_DEPARTAMENTO
FROM EMPLEADO;




