CREATE TABLE GAMA_PRODUCTO
(
	GAMA VARCHAR2(50),
	DESCRIPCION_TEXTO VARCHAR2(500),
	DESCRIPCION_HTML VARCHAR2(500),
	IMAGEN VARCHAR2(256),
	CONSTRAINT PK_GAMA_PRODUCTO PRIMARY KEY (GAMA)
);

CREATE TABLE PRODUCTO
(
	CODIGO_PRODUCTO VARCHAR2(15),
	NOMBRE VARCHAR2(70),
	GAMA VARCHAR2(50),
	DIMENSIONES VARCHAR2(25),
	PROVEEDOR VARCHAR2(50),
	DESCRIPCION VARCHAR2(500),
	CANTIDAD_EN_STOCK NUMBER(6),
	PRECIO_VENTA DECIMAL(15,2),
	PRECIO_PROVEEDOR DECIMAL(15,2),
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO_PRODUCTO),
	CONSTRAINT FK1_PRODUCTO FOREIGN KEY (GAMA) REFERENCES GAMA_PRODUCTO(GAMA)
);

/*CREATE TABLE OFICINA
(
	CODIGO_OFICINA VARCHAR2(10)
);*/