CREATE TABLE CABALLOS
(
	COD_CABALLO VARCHAR2(4),
	NOMBRE VARCHAR2(20) NOT NULL,
	PESO NUMBER(3),
	FECHA_NAC DATE,
	PROPIETARIO VARCHAR2(25),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT PK_CABALLOS PRIMARY KEY (COD_CABALLO),
	CONSTRAINT CHK1_CABALLOS CHECK (PESO BETWEEN 240 AND 300),
	CONSTRAINT CHK2_CABALLOS CHECK (EXTRACT(YEAR FROM FECHA_NAC)>2000),
	CONSTRAINT CHK3_CABALLOS CHECK (NACIONALIDAD=UPPER(NACIONALIDAD))
);

CREATE TABLE CARRERAS
(
	COD_CARRERA VARCHAR2(4),
	FECHA_Y_HORA DATE,
	IMPORTE_PREMIO NUMBER(6),
	APUESTA_LIMITE DECIMAL(5,2),
	CONSTRAINT PK_CARRERAS PRIMARY KEY (COD_CARRERA),
	CONSTRAINT CHK1_CARRERAS CHECK (EXTRACT(HOUR FROM FECHA_Y_HORA) BETWEEN 9 AND 14 OR EXTRACT(MINUTE FROM FECHA_Y_HORA) BETWEEN 00 AND 30),
	CONSTRAINT CHK2_CARRERAS CHECK (APUESTA_LIMITE<20000)
);

CREATE TABLE PARTICIPACIONES
(
	COD_CABALLO VARCHAR2(4),
	COD_CARRERA VARCHAR2(4),
	DORSAL NUMBER(2) NOT NULL,
	JOCKEY VARCHAR2(10) NOT NULL,
	POSICION_FINAL NUMBER(2),
	CONSTRAINT PK_PARTICIPACIONES PRIMARY KEY (COD_CABALLO,COD_CARRERA),
	CONSTRAINT CHK1_PARTICIPACIONES CHECK (PASICION_FINAL>0),
	CONSTRAINT FK1_PARTICIPACIONES FOREIGN KEY (COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO),
	CONSTRAINT FK2_PARTICIPACIONES FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA) 
);

CREATE TABLE CLIENTES
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI),
	CONSTRAINT CHK1_CLIENTES CHECK (DNI LIKE '^[1-9]{8}[A-Z]$'),
	CONSTRAINT CHK2_CLIENTES CHECK (NACIONALIDAD=UPPER(NACIONALIDAD))
);

CREATE TABLE APUESTAS
(
	DNI_CLIENTE VARCHAR2(10),
	COD_CABALLO VARCHAR2(4),
	COD_CARRERA VARCHAR2(4),
	IMPORTE NUMBER(6) DEFAULT 300,
	TANTOPORUNO DECIMAL(4,2),
	CONSTRAINT PK_APUESTAS PRIMARY KEY (DNI_CLIENTE,COD_CABALLO,COD_CARRERA),
	CONSTRAINT CHK1_APUESTAS CHECK (TANTOPORUNO>1),
	CONSTRAINT FK1_APUESTAS FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES(DNI),
	CONSTRAINT FK2_APUESTAS FOREIGN KEY (COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO),
	CONSTRAINT FK3_APUESTAS FOREIGN KEY (COD_CARRERA) REFERENCES CARRERA(COD_CARRERA)
);




