CREATE TABLE ALUMNOS
(
	CODIGO NUMBER(4),
	NOMBRE VARCHAR2(10),
	APELLIDOS VARCHAR2(20),
	DIRECCION VARCHAR2(40),
	FECHANAC DATE,
	SEXO VARCHAR2(1),
	CONSTRAINT PK_ALUMNOS PRIMARY KEY (CODIGO),
	CONSTRAINT CHK1_ALUMNOS CHECK (SEXO IN ('H','M'))
);

CREATE TABLE PROFESOR 
(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(10),
	APELLIDO1 VARCHAR2(10),
	APELLIDO2 VARCHAR2(10),
	DIRECCION VARCHAR2(40),
	TITULACION VARCHAR2(50),
	CUOTA DECIMAL(15,2),
	CONSTRAINT PK_PROFESOR PRIMARY KEY (DNI)
);

CREATE TABLE CURSO
(
	CODIGO NUMBER(4),
	NOMBRE VARCHAR2(10),
	NUM_MAX_ALUMN NUMBER(5),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	NUM_HORAS DATE,
	DNI_PROFESOR VARCHAR2(9),
	CONSTRAINT PK_CURSO PRIMARY KEY (CODIGO),
	CONSTRAINT FK1_CURSO FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESOR(DNI)
);

INSERT INTO PROFESOR(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,TITULACION,CUOTA)
VALUES ('Juan','Arch','López','32432455','Puerta Negra, 4','Ing. Informática',7500);

INSERT INTO PROFESOR(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,TITULACION,CUOTA)
VALUES ('María','Oliva','Rubio','43215643','Juan Alfonso 32','Lda. Fil. Inglesa',5400);


