CREATE TABLE CLIENTE
(
	DNI VARCHAR2(9),
	Nombre VARCHAR2(10) NOT NULL,
	Apellidos VARCHAR2(40),
	Direccion VARCHAR2(50),
	FechaNac DATE,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI),
	CONSTRAINT CHK1_CLIENTE CHECK (REGEX_LIKE(DNI,'^[0-9]{8}[A-Z]'))
);

CREATE TABLE PROVEEDOR
(
	NIF VARCHAR2(10),
	Nombre VARCHAR2(10) NOT NULL,
	Direccion VARCHAR2(50),
	CONSTRAINT PK_PROVEEDOR PRIMARY KEY (NIF)
);

CREATE TABLE PRODUCTO
(
	Codigo NUMBER(4),
	Nombre VARCHAR2(50),
	Precio DECIMAL(5,2),
	NIF_Proveedor VARCHAR2(10),
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (Codigo),
	CONSTRAINT FK1_PRODUCTO FOREIGN KEY (NIF_Proveedor) REFERENCES PROVEEDOR(NIF)
);

CREATE TABLE COMPRA
(
	DNI_Cliente VARCHAR2(9),
	Codigo_Producto NUMBER(4),
	Fecha DATE,
	CONSTRAINT PK_COMPRA PRIMARY KEY (DNI_Cliente,Codigo_Producto,Fecha),
	CONSTRAINT FK1_COMPRA FOREIGN KEY (DNI_Cliente) REFERENCES CLIENTE(DNI),
	CONSTRAINT FK2_COMPRA FOREIGN KEY (Codigo_Producto) REFERENCES PRODUCTO(CODIGO)
);

CREATE SEQUENCE SEQ_CODIGO_PRODUCTO
START WITH 1
INCREMENT BY 1;

CREATE INDEX INX_CLIENTE
ON CLIENTE(Nombre,Apellidos);

INSERT INTO CLIENTE
VALUES ('12345678A','JESÚS','MORILL MARTÍNEZ',NULL,TO_DATE('03/12/06','DD/MM/YY'));

INSERT INTO PROVEEDOR
VALUES ('1234','JUAN',NULL);

INSERT INTO PROVEEDOR
VALUES ('5678','JUAN2',NULL);

INSERT INTO PRODUCTO
VALUES (SEQ_CODIGO_PRODUCTO.NEXTVAL,'PROCESADOR INTEL CORE I-7',349.90,'1234');

INSERT INTO COMPRA
VALUES ('12345678A',SEQ_CODIGO_PRODUCTO.CURRVAL,TO_DATE('3O/01/25','DD/MM/YY'));

UPDATE CLIENTE
SET APELLIDOS='MORILLA MATRÍNEZ'
WHERE Nombre LIKE 'JESÚS';

DELETE FROM PROVEEDOR
WHERE Nombre LIKE 'JUAN2';



